package com.senars;

import com.senars.config.AppConfig;
import com.senars.core.*;
import com.senars.cycle.CognitiveCycle;
import com.senars.systems.Memory;
import dev.langchain4j.model.chat.ChatLanguageModel;
import dev.langchain4j.model.embedding.AllMiniLmL6V2EmbeddingModel;
import dev.langchain4j.model.embedding.EmbeddingModel;
import dev.langchain4j.model.ollama.OllamaChatModel;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.*;

/**
 * An end-to-end integration test for demonstrating the system's ability
 * to use the ApiTool to achieve a goal.
 */
@Disabled("Requires a running Ollama instance and internet access")
public class ApiInteractionIntegrationTest {

    private SystemFactory systemFactory;
    private CognitiveCycle cognitiveCycle;
    private Memory memory;
    private EmbeddingModel embeddingModel;

    @BeforeEach
    void setUp() throws IOException {
        // Use a temporary database for this test to ensure isolation
        Path tempDbPath = Files.createTempDirectory("senars-test-db-");
        tempDbPath.toFile().deleteOnExit();

        // Create a default chat model to pass to the factory constructor
        ChatLanguageModel chatModel = OllamaChatModel.builder()
                .baseUrl(AppConfig.getInstance().getLlmApiUrl())
                .modelName(AppConfig.getInstance().getLlmModelName())
                .timeout(java.time.Duration.ofSeconds(AppConfig.getInstance().getLlmApiTimeout()))
                .build();

        systemFactory = new SystemFactory(chatModel, tempDbPath);
        cognitiveCycle = systemFactory.getCognitiveCycle();
        memory = systemFactory.memory;
        embeddingModel = new AllMiniLmL6V2EmbeddingModel();
    }

    @Test
    void testApiInteractionForBtcPrice() throws Exception {
        // 1. Load the new API interaction schema into memory
        List<Thought> apiSchemaList = Genesis.loadSchemasFromFile("api_interaction_schema.json", embeddingModel);
        assertFalse(apiSchemaList.isEmpty(), "API schema should be loaded");
        Thought apiSchema = apiSchemaList.getFirst();
        memory.saveThought(apiSchema);
        System.out.println("Loaded API schema into memory: " + apiSchema.content().symbolic());

        // 2. Create the initial goal
        String goalText = "What is the current price of Bitcoin in USD?";
        List<Double> goalEmbedding = embeddingModel.embed(goalText).content().vectorAsList().stream()
                .map(Float::doubleValue)
                .collect(Collectors.toList());

        Thought goal = new Thought(
                UUID.randomUUID().toString(),
                new ThoughtContent(goalText, null, goalEmbedding, null, null, null, null),
                new ThoughtState(1.0, 100.0, 1.0), // High salience
                new ThoughtMeta(ThoughtType.GOAL, ThoughtOrigin.USER, Collections.emptyList(), Instant.now())
        );
        memory.saveThought(goal);
        // The SalienceAttention mechanism should pick up the new high-salience goal from memory.
        System.out.println("Created and saved initial goal: " + goalText);


        // 3. Run the cognitive cycle for a few steps
        for (int i = 0; i < 10; i++) {
            System.out.println("--- Cycle " + (i + 1) + " ---");
            cognitiveCycle.step();
            Thread.sleep(500); // Increased delay for network calls
        }

        // 4. Verify the outcome
        List<Thought> reports = memory.getAllThoughts().stream()
                .filter(t -> t.metadata().type() == ThoughtType.REPORT)
                .collect(Collectors.toList());

        assertFalse(reports.isEmpty(), "No reports were generated by the end of the test.");

        System.out.println("Generated Reports:");
        reports.forEach(r -> System.out.println("- " + r.content().text()));

        Optional<Thought> finalReport = reports.stream()
                .filter(r -> r.content().text().toLowerCase().contains("bitcoin") && r.content().text().toLowerCase().contains("usd"))
                .findFirst();

        assertTrue(finalReport.isPresent(), "No report found containing the answer about Bitcoin price in USD.");

        String reportText = finalReport.get().content().text().toLowerCase();
        System.out.println("\nFinal Report Found: " + reportText);
        assertTrue(reportText.contains("price"), "The final report should mention the 'price'.");
        // Check for a number, which would be the price itself
        assertTrue(reportText.matches(".*\\d+.*"), "The final report should contain a number representing the price.");
    }
}
