package com.senars.logic;

import com.senars.core.*;
import com.senars.events.EventBus;
import com.senars.events.Events;
import com.senars.systems.Memory;
import dev.langchain4j.data.message.UserMessage;
import dev.langchain4j.model.chat.ChatLanguageModel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.Instant;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Implementation of the Unified Causal Reasoner (UCR).
 * This class handles both forward planning and backward analysis (credit/blame assignment).
 * Designed to support concurrent reasoning requests for parallel execution.
 */
public class UnifiedCausalReasonerImpl implements UnifiedCausalReasoner {

    private static final Logger LOGGER = LoggerFactory.getLogger(UnifiedCausalReasonerImpl.class);
    private static final double DEFAULT_REINFORCEMENT_FACTOR = 0.1; // Learn moderately from success
    private static final double DEFAULT_BLAME_FACTOR = 0.3;       // Learn aggressively from failure
    private static final double DECAY_FACTOR = 0.9; // How much less to blame/reward thoughts further up the causal chain

    private final Memory memory;
    private final EventBus eventBus;
    private final ChatLanguageModel chatModel;
    private final double reinforcementFactor;
    private final double blameFactor;

    public UnifiedCausalReasonerImpl(Memory memory, EventBus eventBus, ChatLanguageModel chatModel) {
        this(memory, eventBus, chatModel, DEFAULT_REINFORCEMENT_FACTOR, DEFAULT_BLAME_FACTOR);
    }

    public UnifiedCausalReasonerImpl(Memory memory, EventBus eventBus, ChatLanguageModel chatModel, double reinforcementFactor, double blameFactor) {
        this.memory = Objects.requireNonNull(memory);
        this.eventBus = Objects.requireNonNull(eventBus);
        this.chatModel = Objects.requireNonNull(chatModel);
        this.reinforcementFactor = reinforcementFactor;
        this.blameFactor = blameFactor;
    }

    @Override
    public List<Thought> reason(Thought startingThought, String direction, ReasoningOptions options) {
        if ("forward".equals(direction)) {
            return performForwardReasoning(startingThought, options);
        } else if ("backward".equals(direction)) {
            return performBackwardReasoning(startingThought, options);
        } else {
            throw new IllegalArgumentException("Direction must be either 'forward' or 'backward'");
        }
    }

    @Override
    public List<Thought> simulate(Thought startingThought, ReasoningOptions options) {
        // Perform simulation using the same forward reasoning logic but in simulation mode
        return performForwardReasoning(startingThought, new ReasoningOptions(true, options.getMaxDepth()));
    }

    @Override
    public void processFeedback(Feedback feedback) {
        LOGGER.info("Processing feedback for tool '{}'", feedback.toolName());

        // Adjust clarity of thoughts in the trace based on feedback
        List<String> traceIds = feedback.actionPlan().metadata().trace();
        if (traceIds != null && !traceIds.isEmpty()) {
            boolean isFailure = feedback.status() == ActionStatus.FAILURE;
            double adjustment = isFailure ? -this.blameFactor : this.reinforcementFactor;
            adjustClarityInTrace(traceIds, adjustment, 0);
        }

        // If this is a failure, create a goal to investigate and resolve it
        if (feedback.status() == ActionStatus.FAILURE) {
            createAndPublishFailureGoal(feedback);
        }
    }

    /**
     * Performs forward reasoning to generate new thoughts based on the starting thought.
     * This replaces the Cognitive Processor functionality.
     *
     * @param focusThought The thought to start reasoning from
     * @param options      Additional options for the reasoning process
     * @return A list of new thoughts generated by the reasoning process
     */
    private List<Thought> performForwardReasoning(Thought focusThought, ReasoningOptions options) {
        // For estimation mode, we just estimate effort without full simulation
        if (options.isEstimateOnly()) {
            return performEffortEstimation(focusThought, options);
        }

        // For simulation mode, we don't actually execute actions, just evaluate potential outcomes
        if (options.isSimulate()) {
            return performSimulation(focusThought, options);
        }

        eventBus.publish(new Events.CognitionStartEvent(focusThought));
        try {
            LOGGER.info("Processing thought: {} of type {} using UCR forward reasoning",
                    focusThought.id(), focusThought.metadata().type());

            // 1. Generate potential actions
            List<Thought> potentialActions = generatePotentialActions(focusThought);
            if (potentialActions.isEmpty()) {
                LOGGER.warn("UCR generated no potential actions for thought {}", focusThought.id());
                return Collections.emptyList();
            }
            LOGGER.info("Generated {} potential actions.", potentialActions.size());

            // 2. Simulate each action to predict its outcome
            Map<Thought, Double> simulatedOutcomes = new HashMap<>();
            for (Thought action : potentialActions) {
                List<Thought> simulationResults = performSimulation(action, ReasoningOptions.simulation());
                // For simplicity, we take the clarity of the first simulation result.
                // A more complex model could analyze all results.
                double clarity = simulationResults.isEmpty() ? 0.0 : simulationResults.getFirst().state().clarity();
                simulatedOutcomes.put(action, clarity);
                LOGGER.debug("Simulated action '{}' -> Predicted Clarity: {}", action.content().text(), clarity);
            }

            // 3. Select the best action
            Optional<Thought> bestAction = selectBestAction(simulatedOutcomes);

            if (bestAction.isPresent()) {
                LOGGER.info("Selected best action: '{}'", bestAction.get().content().text());
                return List.of(bestAction.get());
            } else {
                LOGGER.warn("No suitable action was selected after simulation for thought {}", focusThought.id());
                return Collections.emptyList();
            }

        } catch (Exception e) {
            LOGGER.error("Error during UCR forward reasoning for thought: {}", focusThought.id(), e);
            eventBus.publish(new Events.CognitionErrorEvent(focusThought, e));
            return Collections.emptyList();
        } finally {
            eventBus.publish(new Events.CognitionEndEvent(focusThought));
        }
    }

    /**
     * Performs backward reasoning to diagnose root causes of outcomes.
     * This is the diagnostic engine that traces backward through the causal graph.
     *
     * @param focusThought The thought to start reasoning from (typically a REPORT)
     * @param options      Additional options for the reasoning process
     * @return A list of thoughts representing the diagnostic analysis
     */
    private List<Thought> performBackwardReasoning(Thought focusThought, ReasoningOptions options) {
        eventBus.publish(new Events.CognitionStartEvent(focusThought));
        try {
            LOGGER.info("Processing thought: {} of type {} using UCR backward reasoning",
                    focusThought.id(), focusThought.metadata().type());

            // For REPORT thoughts (outcomes), perform root cause analysis
            if (focusThought.metadata().type() == ThoughtType.REPORT) {
                return performRootCauseAnalysis(focusThought, options);
            }

            // For other types, we might want to analyze why this thought exists
            // For now, we'll just return an empty list
            LOGGER.warn("Backward reasoning not implemented for thought type: {}", focusThought.metadata().type());
            return Collections.emptyList();

        } catch (Exception e) {
            LOGGER.error("Error during UCR backward reasoning for thought: {}", focusThought.id(), e);
            eventBus.publish(new Events.CognitionErrorEvent(focusThought, e));
            return Collections.emptyList();
        } finally {
            eventBus.publish(new Events.CognitionEndEvent(focusThought));
        }
    }

    private Optional<Thought> selectBestAction(Map<Thought, Double> simulatedOutcomes) {
        // Select the action with the highest predicted clarity.
        return simulatedOutcomes.entrySet().stream()
                .max(Map.Entry.comparingByValue())
                .map(Map.Entry::getKey);
    }

    /**
     * Performs effort estimation for a thought without full simulation.
     * This is a lightweight mode used by the Attention service.
     *
     * @param focusThought The thought to estimate effort for
     * @param options      Additional options for the estimation process
     * @return A list containing a thought with the estimated effort
     */
    private List<Thought> performEffortEstimation(Thought focusThought, ReasoningOptions options) {
        LOGGER.info("Performing effort estimation for thought: {}", focusThought.id());

        // Simple estimation based on text length and thought type
        String content = focusThought.content().text();
        int contentLength = content != null ? content.length() : 0;

        // Base effort calculation
        double estimatedEffort = contentLength * 0.1;

        // Adjust based on thought type
        switch (focusThought.metadata().type()) {
            case GOAL:
                estimatedEffort *= 1.5; // Goals typically require more effort
                break;
            case SCHEMA:
                estimatedEffort *= 2.0; // Schemas are complex
                break;
            case ACTION:
                estimatedEffort *= 0.8; // Actions are usually straightforward
                break;
            default:
                // No adjustment for other types
                break;
        }

        // Create an estimation result
        String estimationText = String.format(
                "Effort estimation for thought %s: %.2f units",
                focusThought.id(),
                estimatedEffort
        );

        ThoughtContent contentResult = new ThoughtContent(
                estimationText,
                "ucr:effort_estimation",
                null, null, null, null, null
        );

        ThoughtMeta meta = new ThoughtMeta(
                ThoughtType.REPORT,
                ThoughtOrigin.UCR_FORWARD,
                List.of(focusThought.id()),
                Set.of(new CausalLink(focusThought.id(), UUID.randomUUID().toString(), CausalRelationType.COUNTERFACTUAL)),
                Instant.now()
        );

        ThoughtState state = new ThoughtState(1.0, 1.0, 1.0);
        Thought estimationResult = new Thought(UUID.randomUUID().toString(), contentResult, state, meta);

        return List.of(estimationResult);
    }

    /**
     * Performs a simulation of the forward reasoning process without actually executing actions.
     * This is used for predictive grounding to identify potential failures before they happen.
     *
     * @param focusThought The thought to simulate reasoning from
     * @param options      Additional options for the reasoning process
     * @return A list of thoughts representing the simulation result
     */
    private List<Thought> performSimulation(Thought focusThought, ReasoningOptions options) {
        // In simulation mode, we evaluate potential outcomes without executing actions
        // This is used for predictive grounding

        LOGGER.info("Performing simulation for thought: {}", focusThought.id());

        // Simulate potential issues by analyzing the action plan
        List<String> potentialIssues = analyzePotentialIssues(focusThought);

        // Apply constraints if specified
        if (options.getConstraints() != null && options.getConstraints().contains("safety")) {
            // Additional safety checks
            List<String> safetyIssues = performSafetyAnalysis(focusThought);
            potentialIssues.addAll(safetyIssues);
        }

        // Create a simulation result that indicates potential issues
        StringBuilder simulationText = new StringBuilder();
        simulationText.append("Simulation of action plan for thought ").append(focusThought.id()).append("\n");

        if (potentialIssues.isEmpty()) {
            simulationText.append("Simulation result: No potential issues detected. Action plan appears safe to execute.");
        } else {
            simulationText.append("Simulation result: Potential issues detected:\n");
            for (int i = 0; i < potentialIssues.size(); i++) {
                simulationText.append((i + 1)).append(". ").append(potentialIssues.get(i)).append("\n");
            }
        }

        ThoughtContent content = new ThoughtContent(
                simulationText.toString(),
                "ucr:simulation",
                null, null, null, null, null
        );

        ThoughtMeta meta = new ThoughtMeta(
                ThoughtType.REPORT,
                ThoughtOrigin.UCR_FORWARD,
                List.of(focusThought.id()),
                Set.of(new CausalLink(focusThought.id(), UUID.randomUUID().toString(), CausalRelationType.COUNTERFACTUAL)),
                Instant.now()
        );

        // Adjust clarity based on simulation results
        double clarity = potentialIssues.isEmpty() ? 1.0 : 0.5;
        ThoughtState state = new ThoughtState(clarity, 1.0, 1.0);
        Thought simulationResult = new Thought(UUID.randomUUID().toString(), content, state, meta);

        return List.of(simulationResult);
    }

    /**
     * Performs safety analysis on a thought based on governance constraints.
     *
     * @param thought The thought to analyze
     * @return A list of safety issues
     */
    private List<String> performSafetyAnalysis(Thought thought) {
        List<String> safetyIssues = new ArrayList<>();

        // Simple heuristic-based safety analysis
        String content = thought.content().text();
        if (content != null) {
            if (content.toLowerCase().contains("delete system") || content.toLowerCase().contains("rm -rf /")) {
                safetyIssues.add("Critical system deletion command detected");
            }
            if (content.toLowerCase().contains("bypass") && content.toLowerCase().contains("security")) {
                safetyIssues.add("Potential security bypass attempt detected");
            }
        }

        return safetyIssues;
    }

    /**
     * Analyzes a thought for potential issues during simulation.
     * This is a simplified version that would be replaced with full LLM integration.
     *
     * @param thought The thought to analyze
     * @return A list of potential issues
     */
    private List<String> analyzePotentialIssues(Thought thought) {
        List<String> issues = new ArrayList<>();

        // Simple heuristic-based analysis
        String content = thought.content().text();
        if (content != null) {
            if (content.toLowerCase().contains("delete") || content.toLowerCase().contains("remove")) {
                issues.add("Potential destructive action detected");
            }
            if (content.toLowerCase().contains("critical") || content.toLowerCase().contains("important")) {
                issues.add("Action affects critical system components");
            }
            if (content.toLowerCase().contains("user") && content.toLowerCase().contains("data")) {
                issues.add("Action may affect user data");
            }
        }

        // In a real implementation, this would involve complex LLM analysis
        // of the action plan against safety principles and system constraints

        return issues;
    }

    /**
     * Performs root cause analysis on a REPORT thought to identify the root causes
     * of the outcome described in the report.
     */
    private List<Thought> performRootCauseAnalysis(Thought reportThought, ReasoningOptions options) {
        LOGGER.info("Performing root cause analysis for report: {}", reportThought.id());

        // Get the causal chain leading to this report
        List<Thought> trace = memory.getTrace(reportThought.id());

        if (trace.isEmpty()) {
            LOGGER.warn("No trace found for report {}. Cannot perform root cause analysis.", reportThought.id());
            return Collections.emptyList();
        }

        // The root cause is typically the first thought in the trace that isn't a system-generated thought
        Thought rootCause = null;
        for (Thought thought : trace) {
            // Skip system-generated thoughts
            if (thought.metadata().origin() != ThoughtOrigin.SYSTEM &&
                    thought.metadata().origin() != ThoughtOrigin.UCR_FORWARD &&
                    thought.metadata().origin() != ThoughtOrigin.UCR_BACKWARD) {
                rootCause = thought;
                break;
            }
        }

        if (rootCause == null) {
            // If we couldn't find a non-system root cause, use the first thought in the trace
            rootCause = trace.getFirst();
        }

        // Create an analysis result
        StringBuilder analysisText = new StringBuilder();
        analysisText.append("Root cause analysis for report ").append(reportThought.id()).append("\n");
        analysisText.append("Identified root cause: ").append(rootCause.content().text()).append("\n");
        analysisText.append("Root cause type: ").append(rootCause.metadata().type()).append("\n");
        analysisText.append("Root cause origin: ").append(rootCause.metadata().origin()).append("\n");

        ThoughtContent content = new ThoughtContent(
                analysisText.toString(),
                "ucr:root_cause_analysis",
                null, null, null, null, null
        );

        Set<CausalLink> causalLinks = Set.of(
                new CausalLink(rootCause.id(), reportThought.id(), CausalRelationType.DIRECT_CAUSATION)
        );

        ThoughtMeta meta = new ThoughtMeta(
                ThoughtType.REPORT,
                ThoughtOrigin.UCR_BACKWARD,
                List.of(rootCause.id(), reportThought.id()),
                causalLinks,
                Instant.now()
        );

        ThoughtState state = new ThoughtState(1.0, 1.0, 1.0);
        Thought analysisResult = new Thought(UUID.randomUUID().toString(), content, state, meta);

        // Adjust clarity of the root cause based on the report outcome
        adjustClarityBasedOnReport(reportThought, rootCause);

        return List.of(analysisResult);
    }

    /**
     * Adjusts the clarity of a thought based on the outcome described in a report
     */
    private void adjustClarityBasedOnReport(Thought reportThought, Thought rootCause) {
        // Determine if this is a success or failure report
        String reportText = reportThought.content().text();
        boolean isFailure = reportText != null &&
                (reportText.toLowerCase().contains("failed") ||
                        reportText.toLowerCase().contains("error") ||
                        reportText.toLowerCase().contains("problem"));

        double adjustment = isFailure ? -this.blameFactor : this.reinforcementFactor;

        double currentClarity = rootCause.state().clarity();
        double newClarity = Math.max(0.0, Math.min(1.0, currentClarity + adjustment));

        if (Math.abs(newClarity - currentClarity) > 1e-9) {
            Thought updatedThought = new Thought(
                    rootCause.id(),
                    rootCause.content(),
                    new ThoughtState(newClarity, rootCause.state().salience(), rootCause.state().activation()),
                    rootCause.metadata()
            );
            memory.saveThought(updatedThought);
            eventBus.publish(new Events.ClarityUpdatedEvent(updatedThought.id(), currentClarity, newClarity));
            LOGGER.debug("Updated clarity of root cause thought {} from {} to {}",
                    updatedThought.id(), String.format("%.4f", currentClarity), String.format("%.4f", newClarity));
        }
    }

    private void adjustClarityInTrace(List<String> traceIds, double initialAdjustment, int startDecay) {
        int traceSize = traceIds.size();
        for (int i = 0; i < traceSize; i++) {
            String thoughtId = traceIds.get(i);
            int decaySteps = startDecay + (traceSize - 1 - i);
            memory.getThoughtById(thoughtId).ifPresent(thoughtToUpdate ->
                    adjustClarityOfSingleThought(thoughtToUpdate, initialAdjustment, decaySteps));
        }
    }

    private void adjustClarityOfSingleThought(Thought thoughtToUpdate, double initialAdjustment, int decaySteps) {
        double decayedAdjustment = initialAdjustment * Math.pow(DECAY_FACTOR, decaySteps);

        double currentClarity = thoughtToUpdate.state().clarity();
        double newClarity = Math.max(0.0, Math.min(1.0, currentClarity + decayedAdjustment));

        if (Math.abs(newClarity - currentClarity) > 1e-9) {
            Thought updatedThought = new Thought(
                    thoughtToUpdate.id(),
                    thoughtToUpdate.content(),
                    new ThoughtState(newClarity, thoughtToUpdate.state().salience(), thoughtToUpdate.state().activation()),
                    thoughtToUpdate.metadata()
            );
            memory.saveThought(updatedThought);
            eventBus.publish(new Events.ClarityUpdatedEvent(updatedThought.id(), currentClarity, newClarity));
            LOGGER.debug("Updated clarity of thought {} (decay steps: {}) from {} to {} (adjustment: {})",
                    updatedThought.id(), decaySteps, String.format("%.4f", currentClarity), String.format("%.4f", newClarity), String.format("%.4f", decayedAdjustment));
        }
    }

    private void createAndPublishFailureGoal(Feedback feedback) {
        String goalText = String.format("Investigate and resolve failure of tool '%s'. Error: %s",
                feedback.toolName(), feedback.output());

        ThoughtContent content = new ThoughtContent(goalText, null, null, null, null, null, null);

        // This goal should trace back to the failed action plan
        List<String> trace = List.of(feedback.actionPlan().id());
        ThoughtMeta meta = new ThoughtMeta(ThoughtType.GOAL, ThoughtOrigin.UCR_BACKWARD, trace, Instant.now());

        // Give it high salience to ensure it is picked up quickly
        ThoughtState state = new ThoughtState(1.0, 100.0, 1.0);

        Thought failureGoal = new Thought(UUID.randomUUID().toString(), content, state, meta);
        LOGGER.info("Generated new failure-driven goal: {}", failureGoal.id());

        // Publish the new goal to the event bus so the cognitive cycle can add it to the attention funnel
        eventBus.publish(new Events.NewThoughtCreatedEvent(failureGoal));
    }

    private List<Thought> generatePotentialActions(Thought focusThought) {
        String prompt = String.format(
                """
                        Given the current thought: '%s'
                        
                        Brainstorm 3 potential, distinct, and actionable next steps. The output must be a valid JSON array of strings.
                        
                        Example:
                        ["Step 1 text...", "Step 2 text...", "Step 3 text..."]
                        """,
                focusThought.content().text()
        );

        String response = chatModel.generate(UserMessage.from(prompt)).content().text();

        List<Thought> actionThoughts = new ArrayList<>();
        try {
            // A simple regex to find strings within a JSON array.
            // It handles escaped quotes but is not a full JSON parser.
            Pattern pattern = Pattern.compile("\"(.*?)(?<!\\\\)\"");
            Matcher matcher = pattern.matcher(response);

            while (matcher.find()) {
                String actionText = matcher.group(1);

                ThoughtContent content = new ThoughtContent(
                        actionText,
                        "ucr:potential_action",
                        null, null, null, null, null
                );

                Set<CausalLink> causalLinks = Set.of(
                        new CausalLink(focusThought.id(), UUID.randomUUID().toString(), CausalRelationType.DIRECT_CAUSATION)
                );

                ThoughtMeta meta = new ThoughtMeta(
                        ThoughtType.ACTION,
                        ThoughtOrigin.UCR_FORWARD,
                        List.of(),
                        causalLinks,
                        Instant.now()
                );

                ThoughtState state = new ThoughtState(1.0, 1.0, 1.0);
                Thought actionPlan = new Thought(UUID.randomUUID().toString(), content, state, meta);
                actionThoughts.add(actionPlan);
            }
        } catch (Exception e) {
            LOGGER.error("Failed to parse potential actions from LLM response: {}", response, e);
            return Collections.emptyList();
        }

        return actionThoughts;
    }
}