package com.senars.logic;

import com.senars.core.*;
import com.senars.events.EventBus;
import com.senars.events.Events;
import com.senars.systems.Memory;
import dev.langchain4j.model.chat.ChatLanguageModel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.Instant;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import dev.langchain4j.data.message.UserMessage;

/**
 * Implementation of the Unified Causal Reasoner (UCR).
 * This class handles both forward planning and backward analysis (credit/blame assignment).
 */
public class UnifiedCausalReasonerImpl implements UnifiedCausalReasoner {

    private static final Logger LOGGER = LoggerFactory.getLogger(UnifiedCausalReasonerImpl.class);
    private static final double DEFAULT_REINFORCEMENT_FACTOR = 0.1; // Learn moderately from success
    private static final double DEFAULT_BLAME_FACTOR = 0.3;       // Learn aggressively from failure
    private static final double DECAY_FACTOR = 0.9; // How much less to blame/reward thoughts further up the causal chain

    private final Memory memory;
    private final EventBus eventBus;
    private final ChatLanguageModel chatModel;
    private final double reinforcementFactor;
    private final double blameFactor;

    public UnifiedCausalReasonerImpl(Memory memory, EventBus eventBus, ChatLanguageModel chatModel) {
        this(memory, eventBus, chatModel, DEFAULT_REINFORCEMENT_FACTOR, DEFAULT_BLAME_FACTOR);
    }

    public UnifiedCausalReasonerImpl(Memory memory, EventBus eventBus, ChatLanguageModel chatModel, double reinforcementFactor, double blameFactor) {
        this.memory = Objects.requireNonNull(memory);
        this.eventBus = Objects.requireNonNull(eventBus);
        this.chatModel = Objects.requireNonNull(chatModel);
        this.reinforcementFactor = reinforcementFactor;
        this.blameFactor = blameFactor;
    }

    @Override
    public List<Thought> reason(Thought startingThought, String direction, ReasoningOptions options) {
        if ("forward".equals(direction)) {
            return performForwardReasoning(startingThought, options);
        } else if ("backward".equals(direction)) {
            // This would be for explicit backward reasoning, but we primarily use processFeedback for that
            throw new UnsupportedOperationException("Explicit backward reasoning not yet implemented");
        } else {
            throw new IllegalArgumentException("Direction must be either 'forward' or 'backward'");
        }
    }

    @Override
    public List<Thought> simulate(Thought startingThought, ReasoningOptions options) {
        // Perform simulation using the same forward reasoning logic but in simulation mode
        return performForwardReasoning(startingThought, new ReasoningOptions(true, options.getMaxDepth()));
    }

    /**
     * Performs forward reasoning to generate new thoughts based on the starting thought.
     * This replaces the Cognitive Processor functionality.
     *
     * @param focusThought The thought to start reasoning from
     * @param options      Additional options for the reasoning process
     * @return A list of new thoughts generated by the reasoning process
     */
    private List<Thought> performForwardReasoning(Thought focusThought, ReasoningOptions options) {
        // For simulation mode, we don't actually execute actions, just evaluate potential outcomes
        if (options.isSimulate()) {
            return performSimulation(focusThought, options);
        }

        eventBus.publish(new Events.CognitionStartEvent(focusThought));
        try {
            LOGGER.info("Processing thought: {} of type {} using UCR forward reasoning",
                    focusThought.id(), focusThought.metadata().type());

            // 1. Generate potential actions
            List<Thought> potentialActions = generatePotentialActions(focusThought);
            if (potentialActions.isEmpty()) {
                LOGGER.warn("UCR generated no potential actions for thought {}", focusThought.id());
                return Collections.emptyList();
            }
            LOGGER.info("Generated {} potential actions.", potentialActions.size());

            // 2. Simulate each action to predict its outcome
            Map<Thought, Double> simulatedOutcomes = new HashMap<>();
            for (Thought action : potentialActions) {
                List<Thought> simulationResults = performSimulation(action, ReasoningOptions.simulation());
                // For simplicity, we take the clarity of the first simulation result.
                // A more complex model could analyze all results.
                double clarity = simulationResults.isEmpty() ? 0.0 : simulationResults.get(0).state().clarity();
                simulatedOutcomes.put(action, clarity);
                LOGGER.debug("Simulated action '{}' -> Predicted Clarity: {}", action.content().text(), clarity);
            }

            // 3. Select the best action
            Optional<Thought> bestAction = selectBestAction(simulatedOutcomes);

            if (bestAction.isPresent()) {
                LOGGER.info("Selected best action: '{}'", bestAction.get().content().text());
                return List.of(bestAction.get());
            } else {
                LOGGER.warn("No suitable action was selected after simulation for thought {}", focusThought.id());
                return Collections.emptyList();
            }

        } catch (Exception e) {
            LOGGER.error("Error during UCR forward reasoning for thought: {}", focusThought.id(), e);
            eventBus.publish(new Events.CognitionErrorEvent(focusThought, e));
            return Collections.emptyList();
        } finally {
            eventBus.publish(new Events.CognitionEndEvent(focusThought));
        }
    }

    private Optional<Thought> selectBestAction(Map<Thought, Double> simulatedOutcomes) {
        // Select the action with the highest predicted clarity.
        return simulatedOutcomes.entrySet().stream()
                .max(Map.Entry.comparingByValue())
                .map(Map.Entry::getKey);
    }

    /**
     * Performs a simulation of the forward reasoning process without actually executing actions.
     * This is used for predictive grounding to identify potential failures before they happen.
     *
     * @param focusThought The thought to simulate reasoning from
     * @param options      Additional options for the reasoning process
     * @return A list of thoughts representing the simulation result
     */
    private List<Thought> performSimulation(Thought focusThought, ReasoningOptions options) {
        // In simulation mode, we evaluate potential outcomes without executing actions
        // This is used for predictive grounding
        
        LOGGER.info("Performing simulation for thought: {}", focusThought.id());
        
        // Simulate potential issues by analyzing the action plan
        List<String> potentialIssues = analyzePotentialIssues(focusThought);
        
        // Create a simulation result that indicates potential issues
        StringBuilder simulationText = new StringBuilder();
        simulationText.append("Simulation of action plan for thought ").append(focusThought.id()).append("\n");
        
        if (potentialIssues.isEmpty()) {
            simulationText.append("Simulation result: No potential issues detected. Action plan appears safe to execute.");
        } else {
            simulationText.append("Simulation result: Potential issues detected:\n");
            for (int i = 0; i < potentialIssues.size(); i++) {
                simulationText.append((i + 1)).append(". ").append(potentialIssues.get(i)).append("\n");
            }
        }
        
        ThoughtContent content = new ThoughtContent(
                simulationText.toString(),
                "ucr:simulation",
                null, null, null, null, null
        );
        
        ThoughtMeta meta = new ThoughtMeta(
                ThoughtType.REPORT,
                ThoughtOrigin.UCR_FORWARD,
                List.of(focusThought.id()),
                Set.of(new CausalLink(focusThought.id(), UUID.randomUUID().toString(), CausalRelationType.COUNTERFACTUAL)),
                Instant.now()
        );
        
        // Adjust clarity based on simulation results
        double clarity = potentialIssues.isEmpty() ? 1.0 : 0.5;
        ThoughtState state = new ThoughtState(clarity, 1.0, 1.0);
        Thought simulationResult = new Thought(UUID.randomUUID().toString(), content, state, meta);
        
        return List.of(simulationResult);
    }
    
    /**
     * Analyzes a thought for potential issues during simulation.
     * This is a simplified version that would be replaced with full LLM integration.
     *
     * @param thought The thought to analyze
     * @return A list of potential issues
     */
    private List<String> analyzePotentialIssues(Thought thought) {
        List<String> issues = new ArrayList<>();
        
        // Simple heuristic-based analysis
        String content = thought.content().text();
        if (content != null) {
            if (content.toLowerCase().contains("delete") || content.toLowerCase().contains("remove")) {
                issues.add("Potential destructive action detected");
            }
            if (content.toLowerCase().contains("critical") || content.toLowerCase().contains("important")) {
                issues.add("Action affects critical system components");
            }
            if (content.toLowerCase().contains("user") && content.toLowerCase().contains("data")) {
                issues.add("Action may affect user data");
            }
        }
        
        // In a real implementation, this would involve complex LLM analysis
        // of the action plan against safety principles and system constraints
        
        return issues;
    }

    @Override
    public void processFeedback(Feedback feedback) {
        if (feedback == null || feedback.actionPlan() == null) {
            LOGGER.warn("Received feedback with no action plan. Ignoring.");
            return;
        }

        Thought actionPlan = feedback.actionPlan();
        // In the new system, we'll use causalLinks instead of trace
        // For now, we'll still use the trace for backward compatibility
        List<String> traceIds = actionPlan.metadata().trace();

        if (traceIds == null || traceIds.isEmpty()) {
            LOGGER.info("Feedback for action {} has no trace. No thoughts to adjust.", actionPlan.id());
            return;
        }

        double initialAdjustment = switch (feedback.status()) {
            case SUCCESS -> this.reinforcementFactor;
            case FAILURE -> -this.blameFactor;
        };

        LOGGER.info("Processing feedback for action {}. Status: {}. Adjusting clarity for {} thoughts with initial factor {}.",
                actionPlan.id(), feedback.status(), traceIds.size(), String.format("%.4f", initialAdjustment));

        // Adjust clarity of the action plan itself, as it's the most direct cause.
        adjustClarityOfSingleThought(actionPlan, initialAdjustment, 0);

        // Adjust clarity of the other thoughts in the provenance trace
        adjustClarityInTrace(traceIds, initialAdjustment, 1); // Start decay from 1 step away

        // If the action failed, create a new goal to investigate
        if (feedback.status() == ActionStatus.FAILURE) {
            createAndPublishFailureGoal(feedback);
        }
    }

    private void adjustClarityInTrace(List<String> traceIds, double initialAdjustment, int startDecay) {
        int traceSize = traceIds.size();
        for (int i = 0; i < traceSize; i++) {
            String thoughtId = traceIds.get(i);
            int decaySteps = startDecay + (traceSize - 1 - i);
            memory.getThoughtById(thoughtId).ifPresent(thoughtToUpdate ->
                    adjustClarityOfSingleThought(thoughtToUpdate, initialAdjustment, decaySteps));
        }
    }

    private void adjustClarityOfSingleThought(Thought thoughtToUpdate, double initialAdjustment, int decaySteps) {
        double decayedAdjustment = initialAdjustment * Math.pow(DECAY_FACTOR, decaySteps);

        double currentClarity = thoughtToUpdate.state().clarity();
        double newClarity = Math.max(0.0, Math.min(1.0, currentClarity + decayedAdjustment));

        if (Math.abs(newClarity - currentClarity) > 1e-9) {
            Thought updatedThought = new Thought(
                    thoughtToUpdate.id(),
                    thoughtToUpdate.content(),
                    new ThoughtState(newClarity, thoughtToUpdate.state().salience(), thoughtToUpdate.state().activation()),
                    thoughtToUpdate.metadata()
            );
            memory.saveThought(updatedThought);
            eventBus.publish(new Events.ClarityUpdatedEvent(updatedThought.id(), currentClarity, newClarity));
            LOGGER.debug("Updated clarity of thought {} (decay steps: {}) from {} to {} (adjustment: {})",
                    updatedThought.id(), decaySteps, String.format("%.4f", currentClarity), String.format("%.4f", newClarity), String.format("%.4f", decayedAdjustment));
        }
    }

    private void createAndPublishFailureGoal(Feedback feedback) {
        String goalText = String.format("Investigate and resolve failure of tool '%s'. Error: %s",
                feedback.toolName(), feedback.output());

        ThoughtContent content = new ThoughtContent(goalText, null, null, null, null, null, null);

        // This goal should trace back to the failed action plan
        List<String> trace = List.of(feedback.actionPlan().id());
        ThoughtMeta meta = new ThoughtMeta(ThoughtType.GOAL, ThoughtOrigin.UCR_BACKWARD, trace, Instant.now());

        // Give it high salience to ensure it is picked up quickly
        ThoughtState state = new ThoughtState(1.0, 100.0, 1.0);

        Thought failureGoal = new Thought(UUID.randomUUID().toString(), content, state, meta);
        LOGGER.info("Generated new failure-driven goal: {}", failureGoal.id());

        // Publish the new goal to the event bus so the cognitive cycle can add it to the attention funnel
        eventBus.publish(new Events.NewThoughtCreatedEvent(failureGoal));
    }

    private List<Thought> generatePotentialActions(Thought focusThought) {
        String prompt = String.format(
                """
                Given the current thought: '%s'

                Brainstorm 3 potential, distinct, and actionable next steps. The output must be a valid JSON array of strings.

                Example:
                ["Step 1 text...", "Step 2 text...", "Step 3 text..."]
                """,
                focusThought.content().text()
        );

        String response = chatModel.generate(UserMessage.from(prompt));

        List<Thought> actionThoughts = new ArrayList<>();
        try {
            // A simple regex to find strings within a JSON array.
            // It handles escaped quotes but is not a full JSON parser.
            Pattern pattern = Pattern.compile("\"(.*?)(?<!\\\\)\"");
            Matcher matcher = pattern.matcher(response);

            while (matcher.find()) {
                String actionText = matcher.group(1);

                ThoughtContent content = new ThoughtContent(
                        actionText,
                        "ucr:potential_action",
                        null, null, null, null, null
                );

                Set<CausalLink> causalLinks = Set.of(
                        new CausalLink(focusThought.id(), UUID.randomUUID().toString(), CausalRelationType.DIRECT_CAUSATION)
                );

                ThoughtMeta meta = new ThoughtMeta(
                        ThoughtType.ACTION,
                        ThoughtOrigin.UCR_FORWARD,
                        List.of(),
                        causalLinks,
                        Instant.now()
                );

                ThoughtState state = new ThoughtState(1.0, 1.0, 1.0);
                Thought actionPlan = new Thought(UUID.randomUUID().toString(), content, state, meta);
                actionThoughts.add(actionPlan);
            }
        } catch (Exception e) {
            LOGGER.error("Failed to parse potential actions from LLM response: {}", response, e);
            return Collections.emptyList();
        }

        return actionThoughts;
    }
}